# Generated by Django 4.1.7 on 2023-04-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_no',
            new_name='contact_phone',
        ),
    ]
